-- Clean up existing tables if they exist (to fix db reset issues)
drop table if exists public.user_collections cascade;
drop table if exists public.profiles cascade;
drop table if exists public.souvenirs cascade;


-- 1. Master Data: Souvenirs (Synced from Google Sheets)
create table public.souvenirs (
  id bigint generated by default as identity primary key,
  doc_id text unique not null, -- e.g. "2330_2025-06-01"
  code text not null,          -- Stock Code
  name text,                   -- Company Name
  price numeric,               -- Stock Price
  last_buy_date date,          -- Last Buy Date
  meeting_date date,           -- Meeting Date
  meeting_type text,           -- e.g. "股東常會"
  location text,               -- Meeting Location
  souvenir_item text,          -- Souvenir Name
  odd_lot boolean default false, -- Is Odd Lot allowed?
  source_url text,             -- URL
  data_hash text,              -- For sync capability
  status text default 'active',
  updated_at timestamptz default now()
);

-- 2. User Profiles
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  role text default 'user' check (role in ('admin', 'user')),
  created_at timestamptz default now()
);

-- Trigger to create profile on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 3. User Collections (My Gifts)
create table public.user_collections (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  souvenir_id bigint references public.souvenirs(id) not null, -- Link to Master Data
  status text default 'collected' check (status in ('pending', 'collected', 'missed', 'holding')),
  quantity int default 1,
  note text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(user_id, souvenir_id) -- Prevent duplicate entries for same souvenir
);

-- RLS Policies
alter table public.souvenirs enable row level security;
alter table public.profiles enable row level security;
alter table public.user_collections enable row level security;

-- Souvenirs: Public Read, Admin Write (via Sync Script using Service Key)
create policy "Public can view souvenirs" 
  on public.souvenirs for select using (true);

-- Profiles: Users view own
create policy "Users can view own profile" 
  on public.profiles for select using (auth.uid() = id);

-- User Collections: Users CRUD own
create policy "Users can crud own collection" 
  on public.user_collections for all using (auth.uid() = user_id);
-- Create the storage bucket for stock data
insert into storage.buckets (id, name, public)
values ('stock-data', 'stock-data', true)
on conflict (id) do nothing;

-- Set up RLS for the storage bucket
-- Allow public read access to stock-data
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'stock-data' );

-- Allow authenticated users (e.g. scripts/functions with service role or admin users) to upload
-- For simplicity in this demo, we can allow Service Role (which bypasses RLS) or strict admin policies.
-- Here we allow insert if the user is authenticated (adjust as needed for security)
create policy "Authenticated users can upload"
  on storage.objects for insert
  to authenticated
  with check ( bucket_id = 'stock-data' );

-- 4. Scraper Management Tables (Added for Admin Features)

-- Table: scraper_sources
create table if not exists public.scraper_sources (
  id bigint generated by default as identity primary key,
  source_name text not null,
  source_url text not null,
  method text default 'GET', -- Ensure this column exists
  target_rules jsonb default '{}'::jsonb,
  is_active boolean default true,
  last_scraped_at timestamptz,
  created_at timestamptz default now()
);

-- Fix Schema Drift: Rename selector_config to target_rules if it exists (from old schema)
do $$
begin
  if exists (select 1 from information_schema.columns where table_name = 'scraper_sources' and column_name = 'selector_config') then
    alter table public.scraper_sources rename column selector_config to target_rules;
    alter table public.scraper_sources alter column target_rules set default '{}'::jsonb;
    alter table public.scraper_sources alter column target_rules drop not null;
  end if;
end $$;

-- Ensure 'method' column exists (in case table existed without it)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'scraper_sources' and column_name = 'method') then
    alter table public.scraper_sources add column method text default 'GET';
  end if;
end $$;

-- Table: scraper_logs
create table if not exists public.scraper_logs (
  id bigint generated by default as identity primary key,
  source_id bigint references public.scraper_sources(id) on delete set null,
  status text check (status in ('success', 'failed', 'pending')),
  items_scraped int default 0,
  error_message text,
  executed_at timestamptz default now(),
  completed_at timestamptz
);

-- Enable RLS
alter table public.scraper_sources enable row level security;
alter table public.scraper_logs enable row level security;

-- Policies
-- Drop existing policies to avoid conflicts
drop policy if exists "Admins can manage scraper sources" on public.scraper_sources;
create policy "Admins can manage scraper sources"
  on public.scraper_sources for all
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

drop policy if exists "Authenticated users can view scraper sources" on public.scraper_sources;
create policy "Authenticated users can view scraper sources"
  on public.scraper_sources for select
  using (auth.role() = 'authenticated');

drop policy if exists "Admins can view logs" on public.scraper_logs;
create policy "Admins can view logs"
  on public.scraper_logs for select
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

drop policy if exists "Authenticated users can insert logs" on public.scraper_logs;
create policy "Authenticated users can insert logs"
  on public.scraper_logs for insert
  with check (auth.role() = 'authenticated');

-- Insert a default source for Sinotrade
insert into public.scraper_sources (source_name, source_url, method)
values ('永豐金 - 股東會紀念品', 'https://www.sinotrade.com.tw/richclub/tools/gifts', 'GET')
on conflict do nothing;
-- Insert MOPS source
insert into public.scraper_sources (source_name, source_url, method, target_rules)
values (
  '公開資訊觀測站 (MOPS) - 股東會紀念品', 
  'https://mops.twse.com.tw/mops/web/ajax_t51sb01', 
  'POST',
  '{"form_data": {"encodeURIComponent": "1", "step": "1", "firstin": "1", "off": "1", "TYPEK": "sii"}}'::jsonb
)
on conflict do nothing;
-- Insert HiStock source
insert into public.scraper_sources (source_name, source_url, method, target_rules)
values (
  'HiStock 嗨投資 - 股東會紀念品', 
  'https://histock.tw/stock/gift.aspx', 
  'GET',
  '{"selector": ".stock-gift table tr"}'::jsonb
)
on conflict do nothing;
-- Insert HiStock source
insert into public.scraper_sources (source_name, source_url, method, target_rules)
values (
  'HiStock 嗨投資 - 股東會紀念品', 
  'https://histock.tw/stock/gift.aspx', 
  'GET',
  '{"selector": ".stock-gift table tr"}'::jsonb
)
on conflict do nothing;
-- Allow public access to view scraper sources and logs
-- This is useful for development or if we want to show status publicly

create policy "Public can view scraper sources"
  on public.scraper_sources for select
  using (true);

create policy "Public can view scraper logs"
  on public.scraper_logs for select
  using (true);
-- Allow anonymous inserts for seeding data (TEMPORARY DEV POLICY)
-- WARNING: This allows ANYONE to insert into the souvenirs table.
-- Should be disabled in production or replaced with SERVICE_ROLE_KEY usage.

create policy "Allow anon insert for seeding"
  on public.souvenirs for insert
  with check (true);
-- Update temp policy to be more permissive for anon seeding
-- Drop previous one to be safe (or rely on CREATE OR REPLACE if supported, but POLICY doesn't support REPLACE)

drop policy if exists "Allow anon insert for seeding" on public.souvenirs;

create policy "Allow anon insert for seeding"
  on public.souvenirs for insert
  to anon
  with check (true);

create policy "Allow anon select for seeding"
  on public.souvenirs for select
  to anon
  using (true);
-- Add RLS policies to allow Admins to manage souvenirs (Insert/Update)

-- 1. Policy for INSERT
drop policy if exists "Admins can insert souvenirs" on public.souvenirs;
create policy "Admins can insert souvenirs"
  on public.souvenirs for insert
  with check (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

-- 2. Policy for UPDATE
drop policy if exists "Admins can update souvenirs" on public.souvenirs;
create policy "Admins can update souvenirs"
  on public.souvenirs for update
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

-- 3. Policy for DELETE (Optional but good for full management)
drop policy if exists "Admins can delete souvenirs" on public.souvenirs;
create policy "Admins can delete souvenirs"
  on public.souvenirs for delete
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );
-- Force update charles771114@gmail.com to admin
update public.profiles
set role = 'admin'
where email = 'charles771114@gmail.com';
