
-- 4. Scraper Management Tables (Added for Admin Features)

-- Table: scraper_sources
create table if not exists public.scraper_sources (
  id bigint generated by default as identity primary key,
  source_name text not null,
  source_url text not null,
  method text default 'GET', -- Ensure this column exists
  target_rules jsonb default '{}'::jsonb,
  is_active boolean default true,
  last_scraped_at timestamptz,
  created_at timestamptz default now()
);

-- Fix Schema Drift: Rename selector_config to target_rules if it exists (from old schema)
do $$
begin
  if exists (select 1 from information_schema.columns where table_name = 'scraper_sources' and column_name = 'selector_config') then
    alter table public.scraper_sources rename column selector_config to target_rules;
    alter table public.scraper_sources alter column target_rules set default '{}'::jsonb;
    alter table public.scraper_sources alter column target_rules drop not null;
  end if;
end $$;

-- Ensure 'method' column exists (in case table existed without it)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'scraper_sources' and column_name = 'method') then
    alter table public.scraper_sources add column method text default 'GET';
  end if;
end $$;

-- Table: scraper_logs
create table if not exists public.scraper_logs (
  id bigint generated by default as identity primary key,
  source_id bigint references public.scraper_sources(id) on delete set null,
  status text check (status in ('success', 'failed', 'pending')),
  items_scraped int default 0,
  error_message text,
  executed_at timestamptz default now(),
  completed_at timestamptz
);

-- Enable RLS
alter table public.scraper_sources enable row level security;
alter table public.scraper_logs enable row level security;

-- Policies
-- Drop existing policies to avoid conflicts
drop policy if exists "Admins can manage scraper sources" on public.scraper_sources;
create policy "Admins can manage scraper sources"
  on public.scraper_sources for all
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

drop policy if exists "Authenticated users can view scraper sources" on public.scraper_sources;
create policy "Authenticated users can view scraper sources"
  on public.scraper_sources for select
  using (auth.role() = 'authenticated');

drop policy if exists "Admins can view logs" on public.scraper_logs;
create policy "Admins can view logs"
  on public.scraper_logs for select
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

drop policy if exists "Authenticated users can insert logs" on public.scraper_logs;
create policy "Authenticated users can insert logs"
  on public.scraper_logs for insert
  with check (auth.role() = 'authenticated');

-- Insert a default source for Sinotrade
insert into public.scraper_sources (source_name, source_url, method)
values ('永豐金 - 股東會紀念品', 'https://www.sinotrade.com.tw/richclub/tools/gifts', 'GET')
on conflict do nothing;
