-- Create souvenir_categories table
create table public.souvenir_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  keywords text[] default '{}',
  color text default 'gray',
  icon text,
  sort_order int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- RLS for souvenir_categories
alter table public.souvenir_categories enable row level security;

create policy "Public can view categories" 
  on public.souvenir_categories for select using (true);

create policy "Admins can manage categories" 
  on public.souvenir_categories for all 
  using (
    exists (
      select 1 from public.profiles 
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

-- Modify souvenirs table
alter table public.souvenirs 
add column category_id bigint references public.souvenir_categories(id),
add column classification_status text default 'unclassified' 
  check (classification_status in ('system_matched', 'verified', 'unclassified'));

-- Indexes
create index idx_souvenirs_category_id on public.souvenirs(category_id);
create index idx_souvenirs_classification_status on public.souvenirs(classification_status);

-- Seed Initial Categories (Optional but helpful)
insert into public.souvenir_categories (name, keywords, color) values
('超商商品卡', ARRAY['超商', '全家', '7-11', '商品卡', '超商卡'], 'blue'),
('廚房清潔', ARRAY['洗碗精', '洗衣精', '肥皂', '香皂', '清潔劑', '菜瓜布'], 'green'),
('食品', ARRAY['米', '麵', '醬油', '餅乾', '茶'], 'orange'),
('生活用品', ARRAY['衛生紙', '牙膏', '毛巾', '襪子', '馬克杯'], 'teal')
on conflict (name) do nothing;
