-- Create user_bindings table
create table public.user_bindings (
  user_id uuid references auth.users not null primary key,
  line_user_id text unique,
  binding_code text, -- Temporary code for binding
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Enable RLS
alter table public.user_bindings enable row level security;

-- Policies for user_bindings
create policy "Users can view their own binding"
  on public.user_bindings for select
  using (auth.uid() = user_id);

create policy "Users can update their own binding"
  on public.user_bindings for update
  using (auth.uid() = user_id);
  
create policy "Users can insert their own binding"
  on public.user_bindings for insert
  with check (auth.uid() = user_id);

-- Create notifications table
create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  type text not null, -- e.g. 'souvenir_alert'
  message text not null,
  status text default 'pending' check (status in ('pending', 'sent', 'failed')),
  created_at timestamptz default now()
);

-- Enable RLS
alter table public.notifications enable row level security;

-- Policies for notifications
create policy "Users can view their own notifications"
  on public.notifications for select
  using (auth.uid() = user_id);
