-- Migration: Create user_inventory and migrate data
-- Decouples stock holdings from specific yearly souvenirs.

BEGIN;

-- 1. Create user_inventory table
CREATE TABLE IF NOT EXISTS public.user_inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  stock_code text NOT NULL,
  stock_name text,
  quantity numeric DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(user_id, stock_code)
);

-- 2. Enable RLS
ALTER TABLE public.user_inventory ENABLE ROW LEVEL SECURITY;

-- 3. Add RLS Policies
CREATE POLICY "Users can CRUD own inventory" 
  ON public.user_inventory FOR ALL 
  USING (auth.uid() = user_id);

-- 4. Backfill from existing user_collections (holding status)
-- We take the most recent record for each stock code per user
INSERT INTO public.user_inventory (user_id, stock_code, stock_name, created_at, updated_at)
SELECT DISTINCT ON (uc.user_id, s.code)
  uc.user_id,
  s.code as stock_code,
  s.name as stock_name,
  uc.created_at,
  uc.updated_at
FROM public.user_collections uc
JOIN public.souvenirs s ON uc.souvenir_id = s.id
WHERE uc.status = 'holding'
ORDER BY uc.user_id, s.code, uc.updated_at DESC
ON CONFLICT (user_id, stock_code) DO NOTHING;

-- 5. Add trigger for updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_user_inventory_updated_at ON public.user_inventory;
CREATE TRIGGER set_user_inventory_updated_at
  BEFORE UPDATE ON public.user_inventory
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

COMMIT;
