-- Create inventory_staging table
create table inventory_staging (
  id bigint generated by default as identity primary key,
  import_batch_id uuid not null default gen_random_uuid(), -- Batch ID for tracking
  year int not null,             -- Year of the inventory
  stock_code text,               -- Stock Code (e.g., 2002)
  stock_name text,               -- Stock Name (e.g., China Steel)
  owner_name text not null,      -- Original Owner Name from file
  
  matched_user_id uuid references auth.users(id), -- Linked User ID (populated later)
  status text default 'PENDING', -- PENDING, IMPORTED, IGNORED
  
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Enable RLS
alter table inventory_staging enable row level security;

-- Policies: Admin Access Only
-- Create a policy that allows admins to do everything
create policy "Admins can do everything on inventory_staging"
  on inventory_staging
  for all
  to authenticated
  using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- Indexes for performance
create index idx_inventory_staging_status on inventory_staging(status);
create index idx_inventory_staging_owner_name on inventory_staging(owner_name);
