-- Clean up existing tables if they exist (to fix db reset issues)
drop table if exists public.user_collections cascade;
drop table if exists public.profiles cascade;
drop table if exists public.souvenirs cascade;


-- 1. Master Data: Souvenirs (Synced from Google Sheets)
create table public.souvenirs (
  id bigint generated by default as identity primary key,
  doc_id text unique not null, -- e.g. "2330_2025-06-01"
  code text not null,          -- Stock Code
  name text,                   -- Company Name
  price numeric,               -- Stock Price
  last_buy_date date,          -- Last Buy Date
  meeting_date date,           -- Meeting Date
  meeting_type text,           -- e.g. "股東常會"
  location text,               -- Meeting Location
  souvenir_item text,          -- Souvenir Name
  odd_lot boolean default false, -- Is Odd Lot allowed?
  source_url text,             -- URL
  data_hash text,              -- For sync capability
  status text default 'active',
  updated_at timestamptz default now()
);

-- 2. User Profiles
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  role text default 'user' check (role in ('admin', 'user')),
  created_at timestamptz default now()
);

-- Trigger to create profile on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 3. User Collections (My Gifts)
create table public.user_collections (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  souvenir_id bigint references public.souvenirs(id) not null, -- Link to Master Data
  status text default 'collected' check (status in ('pending', 'collected', 'missed')),
  quantity int default 1,
  note text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(user_id, souvenir_id) -- Prevent duplicate entries for same souvenir
);

-- RLS Policies
alter table public.souvenirs enable row level security;
alter table public.profiles enable row level security;
alter table public.user_collections enable row level security;

-- Souvenirs: Public Read, Admin Write (via Sync Script using Service Key)
create policy "Public can view souvenirs" 
  on public.souvenirs for select using (true);

-- Profiles: Users view own
create policy "Users can view own profile" 
  on public.profiles for select using (auth.uid() = id);

-- User Collections: Users CRUD own
create policy "Users can crud own collection" 
  on public.user_collections for all using (auth.uid() = user_id);
